config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'

  resources :gossips
  resources :users
  resources :cities, only: [:show , :new]
  resources :gossips do
    resources :comments
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :content, presence: true, length: {minimum: 3, maximum: 400, message: "Votre commentaire doit être compris entre 3 et 400 caractères" }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:new, :edit, :create, :update]
  
  def index
    @comments = Comment.all
  end

  def show
    set_comment
  end

  def new
    @comment = Comment.new
  end


  def create
    @comment = Comment.new(content: params[:content], user: User.find(current_user.id), gossip: Gossip.find(params[:gossip_id]))

    if @comment.save
      flash[:success] = "Merci #{@comment.user.first_name} ! Nous avons pu créer votre commentaire : #{@comment.content} "
      redirect_to :controller => 'gossips', :action => 'show' , id: Gossip.find(params[:gossip_id])
    else
      flash[:danger] = "Nous n'avons pas réussi à créer le commentaire pour la (ou les) raison(s) suivante(s) : #{@comment.errors.full_messages.each {|message| message}.join('')}"
      render :action => 'new'
    end
  end

  def edit
    set_comment
    @gossip = Gossip.find(params[:gossip_id])
  end

  def update
    set_comment
    comment_params 
    if @comment.update(comment_params)
      flash[:success] = "Merci #{@comment.user.first_name} ! Nous avons pu modifier votre commentaire : #{@comment.content} "
      redirect_to :controller => 'gossips', :action => 'show' , id: Gossip.find(params[:gossip_id])
    else
      flash[:danger] = "Nous n'avons pas réussi à modifier le commentaire pour la (ou les) raison(s) suivante(s) : #{@comment.errors.full_messages.each {|message| message}.join('')}"
      redirect_to :action => 'edit'
    end
  end

  def destroy
    set_comment
    if @comment.destroy
      flash[:success] = "Merci #{@comment.user.first_name} ! Nous avons pu supprimer le commentaire : #{@comment.content} "
      redirect_to :controller => 'static_pages', :action => 'index'
    else
      flash[:danger] = "Nous n'avons pas réussi à suppimer le commentaire pour la (ou les) raison(s) suivante(s) : #{@comment.errors.full_messages.each {|message| message}.join('')}"
      render :action => 'edit'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
    @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.permit(:content)
    end

    def authenticate_user
      unless current_user 
        flash[:danger] = "Pour commenter un gossip, vous devez être connecté..."
        redirect_to new_session_path
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<h1 class="text-center new">Edit ce commentaire !</h1>
<p class="text-center new">Balance ton nouveau commentaire via le formulaire ci-dessous</p>
<div class="container text-center">
  <form action= <%= gossip_comment_path %> method="POST">
    <input type="hidden" name="_method" value="patch" />
    <div class="form-group">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    </div>
    <div class="form-group">
      <label for="content">Saisis ici le nouveau contenu de ton commentaire:</label>
      <textarea class="form-control" rows="3" placeholder="Entrez ici le contenu de votre commentaire" name='content'></textarea> 
    </div>
    <button type="submit" class="btn btn-danger align-center" style="margin: 20px">Valider</button>
  </form>
  <%= button_to 'Supprimer ce commentaire', gossip_comment_path(@comment), method: 'delete', data: { confirm: 'Voulez-vous vraiment supprimer ce commentaire ?' }  , class: 'btn btn-danger' %>
</div>

app/views/comments/new.html.erb
<h1 class="text-center new">Crée un commentaire !</h1>
<p class="text-center new">Balance ton commentaire via le formulaire ci-dessous</p>
<div class="container text-center">
  <form action= <%= gossip_comments_path %> method="POST">
    <div class="form-group">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    </div>
    <div class="form-group">
      <label for="Content">Saisis ici le contenu de ton commentaire:</label>
      <textarea class="form-control" rows="3" placeholder="Entrez ici le contenu de votre commentaire" name='content'></textarea> 
    </div>
    <button type="submit" class="btn btn-danger align-center">Valider</button>
  </form>
</div>

app/views/comments/show.html.erb
<div class="container">
  <div class ='text-center'>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= @comment.user.first_name %></h5>
        <p class="card-title"> <%= @comment.content %></p>
        <% if is_owner?(@comment.user.id) %>
          <%= link_to 'Editer ce commentaire', edit_gossip_comment_path(:gossip_id => Gossip.find(params[:gossip_id]), :id => Comment.find(params[:id])), class: 'btn btn-outline-danger btn-sm' %>
        <% end %>
        <%= link_to 'Revenir en arrière', gossip_path(:id => Gossip.find(params[:gossip_id])), class: 'btn btn-outline-secondary btn-sm' %>
      </div>
    </div>
  </div>
</div>