config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'

  resources :gossips
  resources :users
  resources :cities, only: [:show , :new]
  resources :gossips do
    resources :comments
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city, optional: true
  has_many :comments
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "CreatePrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "CreatePrivateMessage"
  has_secure_password
  
  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+.)+[^@\s]+\z/, message: "email adress please" } 
  validates :age, presence: true
  validates :password, :presence => true, :confirmation => true, :length => {:within => 6..40}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    params[:user] = User.find(params[:id])
    params[:gossips] = Gossip.where(user_id: params[:user].id)
  end

  def show
    @user = User.find(params[:id])
    @user_city = City.find(@user.city_id)
    @user_gossip_count = Gossip.where(user_id: @user.id).count
  end

  def new
    @new_user = User.new 
    @city = City.all.order(:name)
  end

  def create  
    @new_user = User.new(first_name: params[:first_name], last_name: params[:last_name], age: params[:age], email: params[:email], password: params[:password], description: params[:description],city: City.find(params[:city_id]))

    if @new_user.save
      flash[:success] = "Merci #{@new_user.first_name} ! Nous avons pu créer ton compte ! "
      redirect_to :controller => 'static_pages', :action => 'index'
    else
      flash[:danger] = "Nous n'avons pas réussi à créer ton compte pour la (ou les) raison(s) suivante(s) : #{@new_user.errors.full_messages.each {|message| message}.join('')}"
      render :action => 'new'
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="view jarallax">
  <div class="mask rgba-indigo-slight">
    <div class="container h-100 d-flex justify-content-center align-items-center">
      <div class="row pt-5 mt-3">
        <div class="col-md-12 mb-3">
          <div class="intro-info-content text-center">
            <h1 class="display-3 blue-text mb-5 wow fadeInDown">
              Bonjour <%= params[:user].first_name %> !<br> Comment allez vous aujourd'hui ?
            </h1>
            <h5 class="text-uppercase blue-text mb-5 mt-1 font-weight-bold wow fadeInDown">HEUREUX DE VOUS REVOIR PARMI NOUS</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="text-center" style="margin-bottom: 25px;">
  <%= link_to "Partagez votre gossip", new_gossip_path , class: "btn btn-danger btn-sm m-3" %>
</div>

<div class ='align-middle text-center'>
  <h6 class="withborder">Voici la liste de vos <strong>gossips</strong> :</h6>
      <% params[:gossips].each do |gossip| %>
        <div class="card">
          <div class="card-body">
            <h5 class="mt-0 text-center"><%= gossip.title  %></h5>
            <p class="card-text text-center"> <%= gossip.content %></p>
            <%= link_to "Afficher ce gossip seul", gossip_path(:id => gossip.id), class: 'btn btn-outline-danger btn-sm' %>
          </div>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center new" style="margin: 25px 0">Inscris toi et partage enfin tes meilleurs potins !</h1>
<div class="container text-center">
  <form action= <%= users_path %> method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <div class="form-group">
      <label for="Title">Ton prénom:</label>
      <input type="text" class="form-control"  aria-describedby="authorHelp" placeholder="Entre ici ton prénom" name='first_name'>
    </div>
    <div class="form-group">
      <label for="name">Ton nom:</label>
      <input type="text" class="form-control"  aria-describedby="authorHelp" placeholder="Entre ici ton nom" name='last_name'>
    </div>
    <div class="form-group">
      <label for="age">Ton âge:</label>
      <input type="text" class="form-control"  aria-describedby="authorHelp" placeholder="Entre ici ton âge" name='age'>
    </div>
    <div class="form-group">
      <label for="Description">Ta description:</label>
      <input type="text" class="form-control"  aria-describedby="authorHelp" placeholder="Entre ici ta description" name='description'>
    </div>
    <div class="form-group">
      <label for="Email">Ton email:</label>
      <input type="text" class="form-control"  aria-describedby="authorHelp" placeholder="Entre ici ton email" name='email'>
    </div>
    <div class="form-group">
      <label for="Email">Ta ville:</label>
      <%= select_tag "city_id", options_from_collection_for_select(@city, "id","name"), class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="pasword">Ton mot de passe:</label>
      <input type="password" class="form-control"  aria-describedby="authorHelp" placeholder="Entre ici ton mot de passe" name='password'>
    </div>
    <div class="form-group">
      <label for="password">Confirme ton mot de passe:</label>
      <input type="password" class="form-control"  aria-describedby="authorHelp" placeholder="Entre ici la confirmation de ton mot de passe" name='password_confirmation'>
    </div>
    <button type="submit" class="btn btn-danger align-center">Valider</button>
  </form>
</div>

app/views/users/show.html.erb
<div class ='text-center'>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= @user.first_name %> <%= @user.last_name %></h5>
      <p class="card-title"><strong>Age : </strong> <%= @user.age %></p>
      <p class="card-title"><%= link_to @user_city.name, city_path(:id => @user_city.id) %></p>
      <p class="card-text"> <strong>Bio :</strong><%= @user.description %></p>
      <p class="card-text"> <strong>A rejoint The Gossip Project le : </strong><%= @user.created_at.strftime("%d/%m/%Y") %></p>
      <p class="card-text"> <strong>Le nombre de gossip(s) partagés : </strong><%= @user_gossip_count %></p>
    </div>
  </div>
</div>