config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'

  resources :gossips
  resources :users
  resources :cities, only: [:show , :new]
  resources :gossips do
    resources :comments
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tags, through: :gossips_tags
  has_many :comments
  validates :title, presence: true, length: {minimum: 3, maximum: 50, message: "Votre titre doit être compris entre 3 et 50 caractères" } 
  validates :content, presence: true
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :show, :edit, :create, :update] 

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = Comment.all
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content],user: User.find(current_user.id)) 

    if @gossip.save
      flash[:success] = "Merci #{@gossip.user.first_name} ! Nous avons pu créer le gossip : #{@gossip.title} "
      redirect_to :controller => 'static_pages', :action => 'index'
    else
      flash[:danger] = "Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) : #{@gossip.errors.full_messages.each {|message| message}.join('')}"
      render :action => 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title, :content)
    if @gossip.update(gossip_params)
      flash[:success] = "Merci #{@gossip.user.first_name} ! Nous avons pu modifier le gossip : #{@gossip.title} "
      redirect_to :controller => 'gossips', :action => 'show'
    else
      flash[:danger] = "Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) : #{@gossip.errors.full_messages.each {|message| message}.join('')}"
      render :action => 'edit'
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    if @gossip.destroy
      flash[:success] = "Merci #{@gossip.user.first_name} ! Nous avons pu supprimer le gossip : #{@gossip.title} "
      redirect_to :controller => 'static_pages', :action => 'index' 
    else
      flash[:danger] = "Nous n'avons pas réussi à suppimer le potin pour la (ou les) raison(s) suivante(s) : #{@gossip.errors.full_messages.each {|message| message}.join('')}"
      render :action => 'show'
    end
  end

  private

  def authenticate_user
    unless current_user 
      flash[:danger] = "Pour lire ou partager un gossip vous devez être connecté..."
      redirect_to new_session_path
    end
  end
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<div class="container text-center">
  <h1 style="padding: 15px 0">Editer le gossip</h1>
  <%= form_for @gossip do |f| %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <div class="form-group">
      <label>Titre du gossip</label>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label>Contenu du gossip</label>
      <%= f.text_area :content, class: 'form-control'%>
    </div>
    <button type="submit" class="btn btn-danger align-center">Valider</button>
  <% end %>
</div>

app/views/gossips/new.html.erb
<h1 class="text-center new">Crée un potin !</h1>
<p class="text-center new">Balance ton potin via le formulaire ci-dessous</p>
<div class="container text-center">
  <form action= <%= gossips_path %> method="POST">
    <div class="form-group">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <label for="Title">Saisis ici le titre de ton gossip :</label>
      <input type="text" class="form-control"  aria-describedby="authorHelp" placeholder="Entrez ici le titre de votre gossip" name='title'>
    </div>
    <div class="form-group">
      <label for="Content">Saisis ici le contenu de votre gossip :</label>
      <textarea class="form-control" rows="3" placeholder="Entrez ici le contenu de votre gossip" name='content'></textarea> 
    </div>
    <button type="submit" class="btn btn-danger align-center">Valider</button>
  </form>
</div>

app/views/gossips/show.html.erb
<div class ='align-middle text-center'>
  <div class="card mt-6 ml-6 mr-6" style="height:280px">
    <div class="card-body">
      <h5 class="card-title"><%= @gossip.title %></h5>
      <p class="card-text"><%= @gossip.content %></p>
      <p class="card-title"><%= link_to "#{(@gossip.user.first_name)+ " " +(@gossip.user.last_name)}" , user_path(:id => @gossip.user.id)%></p>
      <p class="card-text"><%= link_to @gossip.user.city.name, city_path(:id => @gossip.user.city.id) %></p>
      <p class="card-title"><%= @gossip.created_at.strftime("%d/%m/%Y") %></p>
      <% if is_owner?(@gossip.user.id) %>
        <%= link_to "Editer ce gossip", edit_gossip_path(:id => @gossip.id), class: 'btn btn-outline-danger btn-sm' %>
        <%= link_to "Supprimer ce gossip", @gossip, method: :delete, data: {confirm: "Voulez-vous vraiment supprimer ce gossip ?"} , class: 'btn btn-danger btn-sm' %>
      <% end %>
    </div>
  </div>
</div>

<div class="text-center" style="padding: 50px 0">
  <%= link_to "Commenter ce gossip", new_gossip_comment_path(:gossip_id => @gossip.id ), class: 'btn btn-outline-danger btn-sm' %>
</div>

<div class="col-12 text-center">
  <% @comments.each do |comment| %>
    <% if comment.gossip_id == @gossip.id %>
      <div class="card">
        <div class="card-body">
          <h5 class="mt-0 text-center"><%= comment.content  %></h5>
          <p class="card-text text-center"> Un commentaire de : <%= link_to comment.user.first_name , user_path(:id => comment.user.id)%></p>
          <%= link_to "Afficher ce commentaire", gossip_comment_path(:id => comment.id, :gossip_id => @gossip.id), class: 'btn btn-outline-secondary btn-sm' %>
          <% if is_owner?(comment.user.id) %>
            <%= link_to 'Editer ce commentaire', edit_gossip_comment_path(:id => comment.id, :gossip_id => @gossip.id), class: 'btn btn-outline-danger btn-sm' %> 
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>