config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'

  resources :gossips
  resources :users
  resources :cities, only: [:show , :new]
  resources :gossips do
    resources :comments
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :content, presence: true, length: {minimum: 3, maximum: 400, message: "Votre commentaire doit être compris entre 3 et 400 caractères" }
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tags, through: :gossips_tags
  has_many :comments
  validates :title, presence: true, length: {minimum: 3, maximum: 50, message: "Votre titre doit être compris entre 3 et 50 caractères" } 
  validates :content, presence: true
end

app/models/gossips_tag.rb
class GossipsTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips, through: :gossips_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city, optional: true
  has_many :comments
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "CreatePrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "CreatePrivateMessage"
  has_secure_password
  
  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+.)+[^@\s]+\z/, message: "email adress please" } 
  validates :age, presence: true
  validates :password, :presence => true, :confirmation => true, :length => {:within => 6..40}
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def show
    @city = City.find(params[:id])
    @gossips = Gossip.joins(:user).where(:user => User.where(city_id: params[:id]))
  end

  def new
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :show, :edit, :create, :update] 

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = Comment.all
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content],user: User.find(current_user.id)) 

    if @gossip.save
      flash[:success] = "Merci #{@gossip.user.first_name} ! Nous avons pu créer le gossip : #{@gossip.title} "
      redirect_to :controller => 'static_pages', :action => 'index'
    else
      flash[:danger] = "Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) : #{@gossip.errors.full_messages.each {|message| message}.join('')}"
      render :action => 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title, :content)
    if @gossip.update(gossip_params)
      flash[:success] = "Merci #{@gossip.user.first_name} ! Nous avons pu modifier le gossip : #{@gossip.title} "
      redirect_to :controller => 'gossips', :action => 'show'
    else
      flash[:danger] = "Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) : #{@gossip.errors.full_messages.each {|message| message}.join('')}"
      render :action => 'edit'
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    if @gossip.destroy
      flash[:success] = "Merci #{@gossip.user.first_name} ! Nous avons pu supprimer le gossip : #{@gossip.title} "
      redirect_to :controller => 'static_pages', :action => 'index' 
    else
      flash[:danger] = "Nous n'avons pas réussi à suppimer le potin pour la (ou les) raison(s) suivante(s) : #{@gossip.errors.full_messages.each {|message| message}.join('')}"
      render :action => 'show'
    end
  end

  private

  def authenticate_user
    unless current_user 
      flash[:danger] = "Pour lire ou partager un gossip vous devez être connecté..."
      redirect_to new_session_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    params[:user] = User.find(params[:id])
    params[:gossips] = Gossip.where(user_id: params[:user].id)
  end

  def show
    @user = User.find(params[:id])
    @user_city = City.find(@user.city_id)
    @user_gossip_count = Gossip.where(user_id: @user.id).count
  end

  def new
    @new_user = User.new 
    @city = City.all.order(:name)
  end

  def create  
    @new_user = User.new(first_name: params[:first_name], last_name: params[:last_name], age: params[:age], email: params[:email], password: params[:password], description: params[:description],city: City.find(params[:city_id]))

    if @new_user.save
      flash[:success] = "Merci #{@new_user.first_name} ! Nous avons pu créer ton compte ! "
      redirect_to :controller => 'static_pages', :action => 'index'
    else
      flash[:danger] = "Nous n'avons pas réussi à créer ton compte pour la (ou les) raison(s) suivante(s) : #{@new_user.errors.full_messages.each {|message| message}.join('')}"
      render :action => 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    return false if session[:user_id].nil?
    return true
  end

  def is_owner?(id)
    if current_user.id == id
      return true
    else
      return 
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application'%>

  </head>

  <body>
    <header>
    <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark  bg-dark scrolling-navbar">
        <%= link_to "The Gossip Project", root_path, :class => "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!--Links-->
          <ul class="navbar-nav mr-auto smooth-scroll">
            <li class="nav-item">
              <%= link_to "Accueil", root_path, :class => "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Notre équipe", team_path, :class => "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Contact", contact_path, :class => "nav-link" %>
            </li>
            <li class="nav-item dropdown ">
              <a class="nav-link dropdown-toggle " id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Votre session
              </a>
              <div class="dropdown-menu " aria-labelledby="navbarDropdown-connexion">
                <% if logged_in? %>
                  <%= link_to current_user.first_name, {controller: "users", action: "index", id: current_user.id}, class: "dropdown-item" %>
                  <%= link_to "Déconnexion", session_path(session.id), method: :delete, class: "dropdown-item" %>
                <% else %>
                  <%= link_to "Inscrivez-vous", {controller: "users", action: "new"}, class: "dropdown-item" %>
                  <%= link_to "Connexion", {controller: "sessions", action: "new"}, class: "dropdown-item" %>
                  <% end %>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <% flash.each do |key, value| %>
      <div class="alert-dismissible fade show alert alert-<%= key %>"><%= value %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      </div>
    <% end %>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
  </body>
</html>